# Generated by Django 5.2 on 2025-04-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_message', models.TextField(default='Thank you for your payment!')),
                ('inactive_message', models.TextField(blank=True, default='This payment link is no longer active.')),
                ('redirect_url', models.URLField(blank=True, default='')),
                ('branding_image', models.ImageField(blank=True, null=True, upload_to='payment_branding/')),
                ('payment_limit', models.PositiveIntegerField(blank=True, default=0, help_text='0 means unlimited')),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
